// APP
export const APP_IS_LOADING = 'APP_IS_LOADING';
export const APP_IS_NOT_LOADING = 'APP_IS_NOT_LOADING';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_CREDIT_CARD_MODAL = 'OPEN_CREDIT_CARD_MODAL';
export const CLOSE_CREDIT_CARD_MODAL = 'CLOSE_CREDIT_CARD_MODAL';

// USER
export const ON_LOGIN = 'ON_LOGIN';
export const ON_REGISTER = 'ON_REGISTER';
export const CHECK_IS_LOGGED_IN = 'CHECK_IS_LOGGED_IN';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_REGISTRATION_ERROR = 'SET_REGISTRATION_ERROR';
export const SET_USER_DATA = 'SET_USER_DATA';
export const ADD_CREDIT_CARD = 'ADD_CREDIT_CARD';

// SUBSCRIPTIONS
export const GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS';
export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const SUBSCRIBE = 'SUBSCRIBE';
export const CANCEL_USER_SUBSCRIPTION = 'CANCEL_USER_SUBSCRIPTION';
export const GET_USER_SUBSCRIPTIONS = 'GET_USER_SUBSCRIPTIONS';
export const SET_USER_SUBSCRIPTIONS = 'SET_USER_SUBSCRIPTIONS';
export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';

// SPOTS
export const GET_SPOTS = 'GET_SPOTS';
export const SET_SPOTS = 'SET_SPOTS';
export const SET_SPOT_ID = 'SET_SPOT_ID';

// CREDITS
export const GET_CREDITS = 'GET_CREDITS';
export const USE_CREDIT = 'USE_CREDIT';
export const SET_CREDITS = 'SET_CREDITS';
